# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HighwayGo < Formula
  desc "The Official Sonr Highway CLI tool for building and deploying services on the Sonr network/blockchain."
  homepage "https://sonr.io"
  version "0.0.1"
  license "GPLv3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sonr-io/highway-go/releases/download/v0.0.1/highwayd-0.0.1-darwin-arm64.tar.gz"
      sha256 "fb10cb9d46fac2404913905ab62115f8539ec84673d046fbe0e3fb5e51739ca7"

      def install
        bin.install "highwayd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonr-io/highway-go/releases/download/v0.0.1/highwayd-0.0.1-darwin-amd64.tar.gz"
      sha256 "4388faf5ec5532f5c68e391bfabd0d4faf0d0c7bcf8c80f65d6dcc1358b82463"

      def install
        bin.install "highwayd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonr-io/highway-go/releases/download/v0.0.1/highwayd-0.0.1-linux-arm64.tar.gz"
      sha256 "ee13a0ba1ec15b14aecf6bd813a617236552d49c5b17dab40ff37e9544a2ef6c"

      def install
        bin.install "highwayd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonr-io/highway-go/releases/download/v0.0.1/highwayd-0.0.1-linux-amd64.tar.gz"
      sha256 "5b0e649f460131a76b401c71999ff5527c0429d29ab26259da7cfad306170e9d"

      def install
        bin.install "highwayd"
      end
    end
  end

  def caveats; <<~EOS
    Run `brew info sonr` for more information, or run `sonr --help`.
  EOS
  end
end
