# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HighwayGo < Formula
  desc "The Official Sonr Highway CLI tool for building and deploying services on the Sonr network/blockchain."
  homepage "https://sonr.io"
  version "0.0.2"
  license "GPLv3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sonr-io/highway-go/releases/download/v0.0.2/highwayd-0.0.2-darwin-arm64.tar.gz"
      sha256 "f0b1b4579a6203e3b5ae6ab1661ce5b28e5239e4b9c13ac944bd9a2333c3f56a"

      def install
        bin.install "highwayd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonr-io/highway-go/releases/download/v0.0.2/highwayd-0.0.2-darwin-amd64.tar.gz"
      sha256 "4e351534dfd971d7ed9cf4629aa88e31f5b91b2475d26abdfd7e3ec1519fd3a1"

      def install
        bin.install "highwayd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sonr-io/highway-go/releases/download/v0.0.2/highwayd-0.0.2-linux-arm64.tar.gz"
      sha256 "998119cef727855c0a695a5f2280135739fa84fe719f5a0894da41d1c50cfc03"

      def install
        bin.install "highwayd"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sonr-io/highway-go/releases/download/v0.0.2/highwayd-0.0.2-linux-amd64.tar.gz"
      sha256 "fbaac8af1b847cf7a3731f2f036b42b4f2e1b88076885c2cbd57418a0d5d2a7b"

      def install
        bin.install "highwayd"
      end
    end
  end

  def caveats; <<~EOS
    Run `brew info sonr` for more information, or run `sonr --help`.
  EOS
  end
end
